### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by jterrell9**
The main change in this merge is that I am now using the comandUtil package that kyle built in my tester. which means I made some changes to the utility. namely, I added code to a handful of commands. Move is pretty much done I think. Just needs some thought regarding exit room. Examine is like 90% there. and this one prompted changes in the room class and stats class and stuff. You'll see. I few other simple commands work, like quit and menu. Also, look at the java console, after the javafx scene pops up. you'll see my tester at work. It will allow you to create a game and try commands. It's cleanup up quite a bit since its early days.

### CODE REVIEW

**Comment by proudpiper** [comment]
Here are my thoughts

- I really liked the simplifications you did on the Item subclasses.
- I like the idea of the convenience methods you're using in the CommandHandler abstract class. I feel like we might be able to find a better implementation or shift the architecture to better suit this. (This is just a feeling, not very concrete ATM, so it might turn out to be perfectly fine).
- The Stats objects default constructor allows for Stats to have a starting health of 0, a max health of 0, and an attack of 0. If I am not mistaken this is the default die setting. Also if an entity is created with these stats and wasn't dead (say we changed the die condition) they would not be able to attack. Perhaps it would be better to not have a default constructor for this class some the dev always has to define the starting details of a Stats object.
- You seem to be using the FileNotFoundException in places it doesn't make sense. This should only be used when searching for or trying to open a file. You can create custom checked exceptions by creating a class that inherits from Exception or you can create custom unchecked exceptions by creating a class that inherits from RuntimeException. 
- As an example, classes like the ExamineCommand class that have to go down the method tree of objects like the Room the activePlayer is in should call getRunnerRoom once and assign the return value to a local Room object. This will keep the code cleaner. This goes for every object a CommandHandler will be accessing repeatedly that would normally have to go through a method chain.
- The help command should behave more like the help command of actual command line utilities. That is what I based mine off of. I'm not saying you have to use that verbatim, but something more BNF-esc with a description would be ideal.
- Enums should not be all caps. Their specific values should be capitalized (i.e, Weekday.MONDAY) but that enum name itself should be named like a class (camel case ftw),
- The "Armour" class is spelled wrong. It should be "Armor".
- I'm still not sure how I feel about the individual classes handling their own description generation. On one hand, it is a great way to split up a LOT of code for printing class info. On the other hand, it really isn't their job to tell a console how to display their info. We might want to look into writing a more robust Console/(whatever we decide to name it) class that handles all of this, simply for proper separation of functionality.
- After this pull request, I think we should abandon the Tester format of running our code. We didn't have a GUI before so our code had no way to be messed with so I can understand why it was created, but now that Will is getting the GUI setup any more work in the Tester class, specifically with the command line, would be somewhat wasted. If we want, we can pull in a unit testing suite for actual testing.

**Comment by jterrell9** [comment]
Thank you,
As far as the FileNotFound exceptions, most of that code was generated by my IDE, and want to confer with you on what and I why it's required by IDE. the Exception class is something I've not had to learn very much yet. This is why I want to do some reading and talk with you. Sometimes, when your errors catch it just quits the application, when I want it to just ask for new input, and it seems like the CommandHandler exception does this. I use a try catch block for the IllegalArgumentException on ParseCommand call, but sometimes it feels like our exception handling is redundant or something.

I renamed Armour to Suit, and forgot to erase the Armour.java file. You'll find this fixed in branch Tester2.0, which also has your help text. I'm also going to do a some more work, and post another pull request by the morning.

The Tester class will be changed to a console class that will simply hold static methods used for formatting output to the Log, or however we decide to do that. I still haven't used your CommandOutputLog object. instead I'm using a method in Tester (which will be in the Console class) called updateRunner(String output) which basically prints and updated stat board, updated map, and prints whatever String is passed to it to the log.

Hopefully after v2 gets merged, william can implement his RunnerGameScene and we can start testing commands directly in the GUI, with the help of the Console class.

**Comment by jterrell9** [comment]
Also, I agree with you about removing the default constructor, but the attack and health need to at least be able to be set to 0 in order for Stats objects that represent modifiers.

**Comment by proudpiper** [comment]
Responses:

- About the FileNotFoundException: I have no idea why your IDE would be adding that. Pretty strange but as long as we aren't trying to read from a file there is no reason for it so we should get rid of it. We can go into detail on error handling on Tuesday.
- About CommandParser/CommandHandler error chain: I agree it seems a bit redundant. The CommandHandler should throw an error on invalid arguments, perhaps the Parser could catch that and format an error message and throw an IllegalArgumentException. Either way, both need to be able to throw exceptions so the game logic can deal with invalid arguments.
- About Stats: Ah, I see. Thanks for the clarification.

New Stuff(or stuff I didn't mention in the last comment):

- I noticed that the GameRunner logic was commented out on this update. Why is that?
- The unsplitArgs function in the CommandHandler class kind of goes against what I was trying to facilitate there. The point of passing a String array is that it exactly mimics the way that command line arguments are passed in a normal command line program. Also it allows for logic based on number and placement of objects. I would prefer that we get rid of that function and base our command handling logic around the standard way of handling args.

**Comment by jterrell9** [comment]
The gameRunner logic is commented out to turn off javafx. it should have been on in this pull request. anyway, look for new pull request.

**Pull request merged**
