### PR TITLE
Jack commands

### PR DESCRIPTION
**Pull request by jterrell9**
This pull request updates the map and stat board when the running game scene is loaded, and after a command is successfully entered. 
The parser doesnt work with multiple word arguments, so only commands like "move east" will work, not "equip Sword of Mourning"
I also created an enter command, which will actually begin the game. Doesnt work yet.

### CODE REVIEW

**Comment by jterrell9** [comment]
The command parser should now work with multi word arguments.

**Comment by proudpiper** [comment]
I like the addition of a player name being passed to the CommandParser as well as all the work you did to make the map and stat board print appropriately.

A few quick questions:

- Why did you add ArrayList code to the CommandParser for creating the argument list? As far as I could tell it was working perfectly fine with just an array and that would be more efficient.
- On the ExamineCommand and MoveCommand why did you remove the argument list length check? This is an important check to make sure the user doesn't pass more arguments to the command than the command can handle. That being said there were some issues with the specific implementation (my bad) but I still believe that the functionality is important.

**Comment by jterrell9** [comment]
You're parse method puts each word after the command into a separate args[] index. Which is fine. But for commands like item <item_name> it requires the argument to be multiple words. So I reworked the parse method to put everything after the command into args[0] and and then starting from args[1] to args[end] is each word. 

We can add the argument l

**Comment by jterrell9** [comment]
We can add the argument list checks back. Sorry they kept throwing errors after I changed the parse method.

**Pull request merged**
